<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Laporan SyakaMarket</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            color: #222;
            margin: 30px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .header h1 {
            margin: 0;
            font-size: 28px;
        }

        .header p {
            margin: 5px 0;
            color: #777;
        }

        .section-title {
            font-size: 18px;
            margin-top: 30px;
            margin-bottom: 15px;
            border-bottom: 2px solid #ddd;
            padding-bottom: 8px;
        }

        .cards {
            width: 100%;
            margin-bottom: 20px;
        }

        .card {
            width: 48%;
            display: inline-block;
            border: 1px solid #ddd;
            padding: 15px;
            margin-bottom: 10px;
            border-radius: 8px;
        }

        .card-title {
            color: #666;
            font-size: 12px;
        }

        .card-value {
            font-size: 20px;
            font-weight: bold;
            margin-top: 8px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table th {
            background: #f3f4f6;
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }

        table td {
            padding: 10px;
            border: 1px solid #ddd;
        }

        .footer {
            margin-top: 40px;
            text-align: right;
            color: #777;
            font-size: 11px;
        }
    </style>
</head>

<body>

    <div class="header">
        <h1>SYAKAMARKET</h1>
        <p>Laporan Sistem Minimarket</p>

        <div style="margin-top:10px;">
            <p><strong>Tanggal:</strong> {{ now()->format('d M Y H:i') }}</p>
            <p><strong>Cabang:</strong> {{ $branchName }}</p>
        </div>
    </div>

    <div class="section-title">Ringkasan Dashboard</div>

    <div class="cards">
        <div class="card">
            <div class="card-title">Total Penjualan</div>
            <div class="card-value">
                Rp {{ number_format($totalSales, 0, ',', '.') }}
            </div>
        </div>

        <div class="card">
            <div class="card-title">Total Transaksi</div>
            <div class="card-value">
                {{ $totalTransactions }}
            </div>
        </div>

        <div class="card">
            <div class="card-title">Total Produk</div>
            <div class="card-value">
                {{ $totalProducts }}
            </div>
        </div>

        <div class="card">
            <div class="card-title">Stock Menipis</div>
            <div class="card-value">
                {{ $lowStock }}
            </div>
        </div>
    </div>

    <div class="section-title">Riwayat Transaksi</div>

    <table>
        <thead>
            <tr>
                <th>Invoice</th>
                <th>Kasir</th>
                <th>Total</th>
                <th>Tanggal</th>
            </tr>
        </thead>
        <tbody>
            @forelse($transactions as $trx)
                <tr>
                    <td>{{ $trx->invoice }}</td>
                    <td>{{ $trx->user->name ?? '-' }}</td>
                    <td>Rp {{ number_format($trx->total, 0, ',', '.') }}</td>
                    <td>{{ $trx->created_at->format('d M Y') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4">Belum ada transaksi</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="section-title">Riwayat Stock</div>

    <table>
        <thead>
            <tr>
                <th>Produk</th>
                <th>Type</th>
                <th>Qty</th>
                <th>User</th>
            </tr>
        </thead>
        <tbody>
            @forelse($stocks as $stock)
                <tr>
                    <td>{{ $stock->product->name ?? '-' }}</td>
                    <td>{{ strtoupper($stock->type) }}</td>
                    <td>{{ $stock->qty }}</td>
                    <td>{{ $stock->user->name ?? '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4">Belum ada pergerakan stock</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by SyakaMarket System
    </div>

</body>

</html>